language: php

php:
  - 7.1

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer

before_install:
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick
  - cp .env.example .env
  - phpenv config-rm xdebug.ini

install:
  - travis_retry yarn global add jscs
  - travis_retry composer global require friendsofphp/php-cs-fixer --no-interaction --no-suggest
  - travis_retry composer install --no-interaction --no-suggest

before_script:
  - php artisan key:generate
  - php artisan passport:keys

script:
  - jscs ./resources/assets/js
  - $HOME/.composer/vendor/bin/php-cs-fixer fix --dry-run
  - vendor/bin/phpunit
